# Generated by Django 2.1.3 on 2019-06-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190619_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default=1, max_length=20, verbose_name='地址名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱'),
        ),
    ]
